name: Run tests

on: [push, pull_request]

# if need master branch of UnitTesting
#  env:
#     UNITTESTING_TAG: master

env:
  PACKAGE: GitSavvy
  SUBLIME_TEXT_VERSION: 3
  UNITTESTING_TAG: master

jobs:
  linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    env:
      TRAVIS_OS_NAME: linux
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.name GitSavvy
          git config --global user.email gitsavvy@gitsavvy.com
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests --coverage
          sh github.sh run_syntax_tests --coverage
      - run: |
          apt-get update
          apt-get install python3-pip -y
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.name GitSavvy
          git config --global user.email gitsavvy@gitsavvy.com
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests --coverage
          # sh github.sh run_syntax_tests --coverage
      - run: |
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.name GitSavvy
          git config --global user.email gitsavvy@gitsavvy.com
      - run: (new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.ps1","github.ps1")
      - run: |
          ./github.ps1 "bootstrap" -verbose
          ./github.ps1 "install_package_control" -verbose
          ./github.ps1 "run_tests" -coverage -verbose
          # ./github.ps1 "run_syntax_tests" -coverage -verbose
      - run: |
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
